# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubpreference',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='usersubpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertimepreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSubPreference',
        ),
        migrations.DeleteModel(
            name='UserTimePreference',
        ),
    ]
