# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_auto_20160423_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subchoice',
            name='url',
        ),
    ]
